funproject_scaffold/config/routes.rb
Rails.application.routes.draw do
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#new"
end

funproject_scaffold/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

funproject_scaffold/app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :size, presence: true
    validates :categories, presence: true
    validates :ingredients, presence: true
    validates :code, presence: true
    validates :image, presence: true
end

funproject_scaffold/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

funproject_scaffold/app/controllers/products_controller.rb
require 'open-uri'
require 'json'

class ProductsController < ApplicationController
  rescue_from ActionController::ParameterMissing, with: :handle_parameter_missing
  before_action :set_product, only: %i[ create ]
  before_action :detail_destroy_product, only: %i[ show destroy ]
  before_action :set_empty_product, only: %i[ new ]


  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
  end

  # POST /products or /products.json
  def create
    if internet_connection("http://www.google.com")
      code = code_params
      if code !~ /\D/
        uri = URI.parse("http://world.openfoodfacts.org/api/v0/product/"+ code +".json")
        str = JSON.parse(uri.read)
        if str["status"] == 1
          params = ActionController::Parameters.new(product: { name: str["product"]["product_name"], size: str["product"]["quantity"], brands: str["product"]["brands"], categories: str["product"]["categories"], ingredients: str["product"]["ingredients_text"], code: code + ".json", image: str["product"]["image_url"] })
          product = Product.new(product_params(params))
          respond_to do |format|
            if product.save
              format.html { redirect_to products_url, notice: "Product Data Successfully Added !!" }
              format.json { render :show, status: :created, location: product }
            else
              set_empty_product
              format.html { 
                flash.now[:error] = "Product Data Failed To Add, Product " + product.errors.full_messages[0] + " In Json File" 
                render :new, status: :unprocessable_entity
              }
              format.json { render json: product.errors, status: :unprocessable_entity }
            end
          end
        else
          set_empty_product
          respond_to do |format|
            format.html {
              flash.now[:error] = 'Upc Code Is Not Valid'
              render :new, status: :unprocessable_entity
            }
            format.json { 
              head :no_content 
            }
          end
        end
      else
        set_empty_product
        respond_to do |format|
          format.html {
            flash.now[:error] = 'Upc Code Must Be Positive Numbers'
            render :new, status: :unprocessable_entity
          }
          format.json { 
            head :no_content 
          }
        end
      end
    else
      set_empty_product
      respond_to do |format|
        format.html {
          flash.now[:error] = 'There Is No Internet Connection'
          render :new, status: :unprocessable_entity
        }
        format.json { 
          head :no_content 
        }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    respond_to do |format|
      if @product.destroy
        format.html { redirect_to products_url, notice: "Product Data Successfully Deleted !!" }
        format.json { head :no_content }
      else
        format.html {
          flash[:error] = 'Product Data Failed To Delete !!'
          redirect_to products_url
        }
        format.json { head :no_content }
      end
    end
  end

  private

    def internet_connection(url)
      begin
        true if URI.open(url)
      rescue
        false
      end
    end

    def handle_parameter_missing(exception)
      set_empty_product
      respond_to do |format|
        format.html {
          flash.now[:error] = 'Upc Code Must Be Filled'
          render :new, status: :unprocessable_entity
        }
        format.json { 
          head :no_content 
        }
      end
    end
    
    def set_product
      product = Product.find_by_code(code_params + ".json")
      if product
        set_empty_product
        respond_to do |format|
            format.html {
              flash.now[:error] = 'Product Data With This Upc Code Is Exists'
              render :new, status: :unprocessable_entity
            }
            format.json { 
              head :no_content 
            }
        end
      end
    end

    def set_empty_product
      @product = Product.new
    end

    def product_params(params)
      params.require(:product).permit(:name, :size, :brands, :categories, :ingredients, :code, :image)
    end

    def detail_destroy_product
      @product = Product.find_by_id(id_params)
      if !@product
        respond_to do |format|
            format.html { 
              flash[:error] = "Product Not Found !!"
              redirect_to products_url
             }
            format.json { head :no_content }
        end
      end
    end

    def code_params
      params.require(:product)
      params[:product].require(:code)
    end

    def id_params
      params.require(:id)
    end
end

funproject_scaffold/app/helpers/application_helper.rb
module ApplicationHelper
end

funproject_scaffold/app/helpers/products_helper.rb
module ProductsHelper
end

funproject_scaffold/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <style>

    label
    {
      font-weight: bold;
    }

    body
    {
      margin-right:2.5%;
      margin-left:2.5%;
      margin-top:2%;
      width:95%;
    }
    
    .message
    {
      color:MediumSeaGreen;
    }

    .error
    {
      color: Red;
    }

  </style>

  <body>
    <%= yield %>
  </body>
</html>

funproject_scaffold/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>

  <div>
    <%= form.label :code, "Upc Code" %>
    <%= form.text_field :code %>
    <b class="error"> <%= flash[:error] %></b>
  </div>

  <br>

  <div>
    <%= form.submit "Submit", class:"btn btn-primary" %> Or <%= link_to '<button type="button" class="btn btn-primary">Cancel</button>'.html_safe, products_path %>
  </div>

<% end %>

funproject_scaffold/app/views/products/_product.html.erb
<tr id="<%= dom_id product %>">
    <td scope="row"><h5 class><%= product.name %></h5></td>
    <td><%= button_to 'Show', product, method: :get, class: "btn btn-primary" %></td>
    <td><%= button_to "Delete", product, method: :delete, class: "btn btn-danger",  form: { data: { turbo_confirm: "Are You Sure To Delete This Product ?" } } %></td>
</tr>

funproject_scaffold/app/views/products/_productdetail.html.erb
<div id="<%= dom_id product %>">
  <h1>Product Detail</h1><br>
  <p><b>Product Name : </b> <%= @product.name %></p>
  <p><b>Size : </b> <%= @product.size %></p>
  <p><b>Categories : </b> <%= @product.categories %></p>
  <p><b>Ingredients : </b> <%= @product.ingredients %></p>
  <p><b>UPC Code : </b> <%= @product.code %></p>
  <img src="<%= @product.image %>" alt="Image Address Is Invalid Or Check Your Internet Connection" width="250px" height="250px">
</div>

funproject_scaffold/app/views/products/index.html.erb
<h2>List Of Products</h2><b class="message"> <%= notice %></b><b class="error"> <%= flash[:error] %></b>
<br><br>

<table class="table" id="products">
    <thead >
        <tr >
            <th scope="col" style="border-top-style:none;">Product</th>
            <th scope="col"style="border-top-style:none;"> </th>
            <th scope="col" style="border-top-style:none;"> </th>
        </tr>
    </thead>
    <tbody>
        <% @products.each do |product| %>
          <%= render product %>
        <% end %>
    </tbody>
</table>

<br>
<h4>Click Here To <%= link_to "Add New product", new_product_path %></h4>

funproject_scaffold/app/views/products/new.html.erb
<p>API : http://world.openfoodfacts.org/api/v0/product/upc_code.json</p>

<br>

<%= render "form", product: @product %>

<br>

<div>
  <h4>Click Here For <%= link_to "List Of Product", products_path %> </h4><br>
</div>

funproject_scaffold/app/views/products/show.html.erb
<%= render "productdetail", product: @product %>

<br>
<h4>Back To <%= link_to "List Of Products", products_path %></h4>